package cat.complai.dto.sqs;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.micronaut.core.annotation.Introspected;

/**
 * SQS message payload for the async complaint letter generation flow.
 *
 * <p>This record is the contract between the API Lambda (publisher) and the worker Lambda
 * (consumer). Any schema change here must be backwards-compatible or deployed atomically
 * to both Lambdas to avoid deserialization failures on in-flight messages.
 *
 * <p>All three identity fields (requesterName, requesterSurname, requesterIdNumber) are
 * required by the time a message is published — the API Lambda must have validated that
 * identity is complete before enqueuing.
 */
@Introspected
public record RedactSqsMessage(
        String complaintText,
        String requesterName,
        String requesterSurname,
        String requesterIdNumber,
        // Pre-determined S3 key where the worker must upload the generated PDF.
        // Generated by the API Lambda and included here so both sides agree on the key
        // without any coordination at upload time.
        String s3Key,
        // Optional: included for traceability and future conversation-history lookup.
        String conversationId,
        // City identifier from the caller's JWT, used by the worker to load the correct
        // procedures context. Required — messages without a cityId are rejected by the worker.
        String cityId
) {
    @JsonCreator
    public static RedactSqsMessage fromJson(
            @JsonProperty("complaintText")     String complaintText,
            @JsonProperty("requesterName")     String requesterName,
            @JsonProperty("requesterSurname")  String requesterSurname,
            @JsonProperty("requesterIdNumber") String requesterIdNumber,
            @JsonProperty("s3Key")             String s3Key,
            @JsonProperty("conversationId")    String conversationId,
            @JsonProperty("cityId")            String cityId) {
        return new RedactSqsMessage(complaintText, requesterName, requesterSurname,
                requesterIdNumber, s3Key, conversationId, cityId);
    }
}
