package cat.complai.controllers.telegram.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

/**
 * Outbound DTO for the Telegram {@code sendDocument} Bot API method.
 *
 * <p>Serialised to JSON and sent as the request body when the bot needs
 * to send a file (typically a PDF generated by the redact flow).
 *
 * @param chatId    unique identifier for the target chat
 * @param document  file URL, file_id, or file contents to send
 * @param caption   optional caption for the document, or {@code null}
 * @param parseMode formatting mode for the caption ({@code "HTML"} or
 *                  {@code "MarkdownV2"}), or {@code null}
 */
@Introspected
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TelegramSendDocumentRequest(
        @JsonProperty("chat_id") long chatId,
        String document,
        @Nullable String caption,
        @JsonProperty("parse_mode") @Nullable String parseMode
) {}
